name: CML

on: [push, pull_request]

jobs:
  cml:
    runs-on: [ubuntu-latest]
    container:
      image: docker://dvcorg/dvc-cml:micro

    steps:
      - uses: actions/checkout@v2

      - name: dvc_action_run
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          cml-setup

          apt-get update && apt-get install -y python-pip && pip install --upgrade pip
          pip install tensorflow wget

          dvc pull -f
          dvc repro train.dvc
          dvc push

          echo "# CML report" >> report.md
          dvc metrics diff --show-json origin/master HEAD | cml-metrics >> report.md
          dvc diff --show-json origin/master HEAD | cml-files >> report.md

          cml-send-report -p report.md 


  # default:
  #   runs-on: ubuntu-latest
  #   # container: docker://davidgortega/dvc:0.1.6

  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: setup python 
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.6

  #     - uses: DavidGOrtega/dvc-action-docker@master
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         repro_targets: eval.dvc
  #         run: |
  #           pip install tensorflow wget &&
  #           github_run
