name: CML

on: [push, pull_request]

jobs:
  cml:
    runs-on: [ubuntu-latest]
    container:
      image: docker://dvcorg/dvc-cml:image

    steps:
      - uses: actions/checkout@v2

      - name: dvc_action_run
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          echo "# CML report 2" >> report.md

          cat assets/logo.png | cml-publish --md 1 >> report.md
          cat report.md
          cml-send-comment report.md 


  # default:
  #   runs-on: ubuntu-latest
  #   # container: docker://davidgortega/dvc:0.1.6

  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: setup python 
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.6

  #     - uses: DavidGOrtega/dvc-action-docker@master
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         repro_targets: eval.dvc
  #         run: |
  #           pip install tensorflow wget &&
  #           github_run
