name: default

on: [push, pull_request]

jobs:
  dvc:
    runs-on: [dvc-cml]

    steps:
      - uses: actions/checkout@v2
      
      - name: dvc_action_run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          baseline: 'HEAD~1'
          repro_targets: eval.dvc
          metrics_format: '0[.][000]'

        run: |
          nvidia-smi
          apt-get update && apt-get install -y python-pip && pip install --upgrade pip
          pip install tensorflow wget
          dvc_action_run


  # default:
  #   runs-on: ubuntu-latest
  #   # container: docker://davidgortega/dvc:0.1.6

  #   steps:
  #     - uses: actions/checkout@v2
      
  #     - name: setup python 
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.6

  #     - uses: DavidGOrtega/dvc-action-docker@master
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         repro_targets: eval.dvc
  #         run: |
  #           pip install tensorflow wget &&
  #           github_run
