name: default

on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    #container: DavidGOrtega/dvc-action-docker@master

    steps:
      - uses: actions/checkout@v2
      
      - name: setup python 
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: setup requirements
        run: |
          pip install tensorflow wget
          ls
          echo hello >> hello.txt
          ls

      - uses: DavidGOrtega/dvc-action-docker@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repro_targets: eval.dvc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            pip install tensorflow wget
            ls
            echo hello >> hello.txt
            ls
        run: |
          pip install tensorflow wget
          ls
          echo hello >> hello.txt
          ls

      - name: test dvcreport
        run: |
          ls
          dvcreport